server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: rate-me
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${postgres.username}
    password: ${postgres.password}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4
      schema: rateme
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: ${spring.datasource.hikari.schema}
    table: flyway-rateme-service-history

application:
  websocket:
    room-path: /room/{roomId}
  redis:
    host: localhost
    port: 6379
    db: 0
    password: ${redis.password}
    min-idle: 5
    max-total: 10
    timeout: 30
  judge:
    url: http://localhost:2358

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, prometheus
eureka:
  client:
    service-url:
      defaultZone: http://rateme:${eureka.password}}@localhost:8761/eureka/
    enabled: false

springdoc:
  swagger-ui:
    path: swagger.html
