### Get all roles

GET http://167.99.141.157:80/api/role
Authorization: Basic admin password

### Get all users

GET http://167.99.141.157:80/api/user
Authorization: Basic admin password

### Get companies

GET http://167.99.141.157:80/api/company
Authorization: Basic admin password

### Get company's contests

GET http://167.99.141.157:80/api/contest?companyName=tinkoff
Authorization: Basic username password

### Get contest's tasks

GET http://167.99.141.157:80/api/contest/tinkoff-contest/tasks?companyName=tinkoff
Authorization: Basic admin password

### Get langauges

GET http://167.99.141.157:80/api/judge/languages
Authorization: Basic username password

### Send submission

POST http://167.99.141.157:80/api/judge/submission
Content-Type: application/json
Authorization: Basic admin password

{
  "taskId": 1,
  "judgeSubmission": {
    "source_code": "#include <iostream>\nint main() { int x, y;\nstd::cin >> x >> y;\nstd::cout << x + y;\nreturn 0;\n}",
    "language_id": 54
  }
}

### Check submission

GET http://167.99.141.157:80/api/judge/submission/1701790759282-1-4
Authorization: Basic admin password